<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ClassBootStrap._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1>Class BootStrap. </h1>
        <h1>Click on Monday of the first week the class will run.<asp:Calendar ID="Calendar1" runat="server"></asp:Calendar>
        </h1>
        <p class="lead">Submit the CSV file from freedom that contains the user information. Do not edit this file.</p>
        <p class="lead">
            <input id="File1" type="file" /></p>
        <p class="lead">
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Schedule" />
        </p>
    </div>

</asp:Content>
